export enum ErrorCode {
  // Generic
  INTERNAL_ERROR = "INTERNAL_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

  // Auth
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID",
  AUTH_MISSING_TOKEN = "AUTH_MISSING_TOKEN",
  AUTH_REFRESH_TOKEN_REVOKED = "AUTH_REFRESH_TOKEN_REVOKED",
  AUTH_EMAIL_IN_USE = "AUTH_EMAIL_IN_USE",
  AUTH_2FA_REQUIRED = "AUTH_2FA_REQUIRED",
  AUTH_2FA_INVALID = "AUTH_2FA_INVALID",
  AUTH_2FA_SETUP_REQUIRED = "AUTH_2FA_SETUP_REQUIRED",
  AUTH_FORBIDDEN = "AUTH_FORBIDDEN",
  AUTH_INSUFFICIENT_ROLE = "AUTH_INSUFFICIENT_ROLE",
  AUTH_MISSING_PERMISSION = "AUTH_MISSING_PERMISSION",

  // Order
  ORDER_NOT_FOUND = "ORDER_NOT_FOUND",
  ORDER_INSUFFICIENT_BALANCE = "ORDER_INSUFFICIENT_BALANCE",
  ORDER_INVALID_SYMBOL = "ORDER_INVALID_SYMBOL",
  ORDER_INVALID_QUANTITY = "ORDER_INVALID_QUANTITY",
  ORDER_INVALID_PRICE = "ORDER_INVALID_PRICE",
  ORDER_CANCEL_FAILED = "ORDER_CANCEL_FAILED",

  // Wallet
  WALLET_INSUFFICIENT_BALANCE = "WALLET_INSUFFICIENT_BALANCE",
  WALLET_ASSET_NOT_FOUND = "WALLET_ASSET_NOT_FOUND",
  WALLET_WITHDRAWAL_NOT_FOUND = "WALLET_WITHDRAWAL_NOT_FOUND",
  WALLET_WITHDRAWAL_INVALID_STATE = "WALLET_WITHDRAWAL_INVALID_STATE",
  WALLET_INVALID_ADDRESS = "WALLET_INVALID_ADDRESS",

  // Admin
  ADMIN_USER_NOT_FOUND = "ADMIN_USER_NOT_FOUND",
  ADMIN_PERMISSION_SELF_REVOKE = "ADMIN_PERMISSION_SELF_REVOKE",
  ADMIN_PERMISSION_LAST_WRITER = "ADMIN_PERMISSION_LAST_WRITER",
  ADMIN_SHARE_LINK_EXPIRED = "ADMIN_SHARE_LINK_EXPIRED",
  ADMIN_SHARE_LINK_NOT_FOUND = "ADMIN_SHARE_LINK_NOT_FOUND",

  // Market
  MARKET_SYMBOL_NOT_FOUND = "MARKET_SYMBOL_NOT_FOUND",
  MARKET_INVALID_INTERVAL = "MARKET_INVALID_INTERVAL",

  // Support
  SUPPORT_TICKET_NOT_FOUND = "SUPPORT_TICKET_NOT_FOUND",
}
